version: '3.8'

services:
  api:
    image: garuda64/api-bymedellin-imageocr:latest
    container_name: api-bymedellin-ocr
    ports:
      - "3000:80"
    environment:
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - RAILS_LOG_TO_STDOUT=true
      - TESSERACT_LANGUAGE=${TESSERACT_LANGUAGE:-spa}
    volumes:
      - ./docker-volumes/logs:/rails/log
      - ./docker-volumes/storage:/rails/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s